name: Clean Commit Generator

on:
  workflow_dispatch:

jobs:
  clean-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Git Konfiguration
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Remote mit Token setzen
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$REPO.git

      - name: 100 beschreibende Commits erstellen
        run: |
          touch cleancommit.txt
          for i in $(seq 1 100); do
            echo "Zeile $i automatisch hinzugefügt." >> cleancommit.txt
            git add cleancommit.txt
            git commit -m "Füge automatisch generierte Zeile $i hinzu, um Clean Commit zu erhalten"
          done
          git push origin main
