name: Daily Log Commit

on:
  schedule:
    - cron: '0 8 * * *' # täglich um 08:00 UTC
  workflow_dispatch:

jobs:
  add-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Append date to log.md
      run: |
        echo "- $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> log.md

    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add log.md
        git commit -m "Add daily log entry $(date -u +"%Y-%m-%d")" || echo "No changes to commit"
        git push
