name: Auto Issue Creator

on:
  workflow_dispatch:

jobs:
  create-issues-1:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Issues 1–20
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          for i in {1..20}; do
            n=$((i))
            gh api -X POST repos/$REPO/issues \
              -f title="Auto Issue $n" \
              -f body="Erstellt in Job 1 – Issue $n" || echo "⚠️ Fehler bei $n"
            echo "✅ [$n/20] erledigt"
            sleep 2
          done

  create-issues-2:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Issues 21–40
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          for i in {21..40}; do
            gh api -X POST repos/$REPO/issues \
              -f title="Auto Issue $i" \
              -f body="Erstellt in Job 2 – Issue $i" || echo "⚠️ Fehler bei $i"
            echo "✅ [$i/20] erledigt"
            sleep 2
          done

  create-issues-3:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Issues 41–60
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          for i in {41..60}; do
            gh api -X POST repos/$REPO/issues \
              -f title="Auto Issue $i" \
              -f body="Erstellt in Job 3 – Issue $i" || echo "⚠️ Fehler bei $i"
            echo "✅ [$i/20] erledigt"
            sleep 2
          done

  create-issues-4:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Issues 61–80
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          for i in {61..80}; do
            gh api -X POST repos/$REPO/issues \
              -f title="Auto Issue $i" \
              -f body="Erstellt in Job 4 – Issue $i" || echo "⚠️ Fehler bei $i"
            echo "✅ [$i/20] erledigt"
            sleep 2
          done

  create-issues-5:
    runs-on: ubuntu-latest
    steps:
      - name: 🌀 Issues 81–100
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          for i in {81..100}; do
            gh api -X POST repos/$REPO/issues \
              -f title="Auto Issue $i" \
              -f body="Erstellt in Job 5 – Issue $i" || echo "⚠️ Fehler bei $i"
            echo "✅ [$i/20] erledigt"
            sleep 2
          done
