name: Create Issues

on:
  workflow_dispatch:

jobs:
  spam:
    runs-on: ubuntu-latest
    steps:
      - name: 🐛 Create 100 Issues
        run: |
          for i in {1..100}; do
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues \
              -d "{\"title\":\"Issue #$i\",\"body\":\"Automatisch generiert – from:workflow\"}"
            echo "🆕 Issue $i erstellt"
            sleep 6
          done

  delete:
    runs-on: ubuntu-latest
    needs: spam
    steps:
      - name: ⏳ Warte 10 Minuten
        run: sleep 600

      - name: 🧹 Lösche Workflow-Issues
        run: |
          issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues?state=open\&per_page=100)
          echo "$issues" | jq -c '.[] | select(.body | contains("from:workflow"))' | while read issue; do
            number=$(echo "$issue" | jq '.number')
            echo "❌ Lösche Issue #$number"
            curl -X PATCH \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$number \
              -d '{"state":"closed"}'
          done
