name: Delete PR Branches

on:
  workflow_dispatch:

jobs:
  delete-pr-branches:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO: ${{ github.repository }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Set remote URL with token
        run: |
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$REPO.git
          git fetch --prune

      - name: Delete branches in batches of 25
        run: |
          branches=( $(git branch -r | grep 'origin/pr643-' | sed 's|origin/||') )
          total=${#branches[@]}
          echo "Found $total branches to delete."

          batch_size=25
          for ((i=0; i<total; i+=batch_size)); do
            echo "Deleting batch from $i to $((i+batch_size-1))"
            batch=( "${branches[@]:i:batch_size}" )
            for branch in "${batch[@]}"; do
              echo "Deleting remote branch $branch"
              git push origin --delete "$branch" || echo "Failed to delete $branch"
            done
          done
