name: Ship it! Achievement Releases

on:
  workflow_dispatch:

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub CLI installieren
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: 10 Releases erstellen
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          for i in $(seq 1 10); do
            gh release create "v1.0.$i" --title "Release $i" --notes "Automatisch generierter Release $i" || echo "Release $i existiert wahrscheinlich schon"
            sleep 3
          done
